# Machine Learning and Predictive Analytics
# Assignment 8

Name: Troy Zhongyi Zhang           
Netid: zhongyiz@uchicago.edu

# Convolutional Neural Network & Classification: 

The objective is to build an image classifier that is capable of properly identifying four different categories of image. 

The data consists of various train and test samples across the four categories of image. You will notice that the data for a specific category is a singular image that has been flipped, rotated, or slightly altered in some way. 

You can use the keras package to solve this problem (https://keras.io/). 

Data for HW: Note that each file is a zip

dataset_train.zip

dataset_test.zip

# 1. Data Processing: 
The train & test data is pretty clean in terms of image data, but we will need to do a bit of prep work to use in our model. 

In [1]:
# 1 - (a)
from keras.preprocessing.image import ImageDataGenerator
train_datagen = ImageDataGenerator(rescale = 1./255,
                                   shear_range = 0.2,
                                   zoom_range = 0.2,
                                   horizontal_flip=True)

Using TensorFlow backend.


In [7]:
# 1 - (b)
train_generator = train_datagen.flow_from_directory('/Users/zhongyizhang/Desktop/UChicago_MSBI/2019Summer/Machine Learning/HWK8/dataset_train/',
                                                    target_size=(64, 64),
                                                    batch_size=32,
                                                    class_mode='categorical')

Found 88 images belonging to 4 classes.


In [8]:
# x, y = train_generator.next()
# for i in range(0,1):
#     image = x[i]
# #     print image

In [9]:
print(train_generator.target_size)

(64, 64)


In [10]:
print(train_generator.classes)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3]


1 - (c)      
The image shape of each training observation is (64, 64, 3).       
There are 4 classes in total we need to predict on.

# 2. Initial Classifier Build: 
Now use keras to build an initial image classifier with the following specifications.

Note: If you get lost, there is great documentation online and homework 7 included details on many of the layers used here.

In [11]:
from keras.models import Sequential
classifier = Sequential()

W0924 19:45:40.387418 4497221056 deprecation_wrapper.py:119] From /Users/zhongyizhang/env/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.



In [40]:
import numpy as np
a=np.ones(10)
b = np.ones(10)*2
c=a*b

In [42]:
d = c+1
d

array([3., 3., 3., 3., 3., 3., 3., 3., 3., 3.])

In [12]:
from keras.layers.convolutional import Conv2D
classifier.add(Conv2D(filters = 32,
                      kernel_size = (3,3),
                      input_shape = (64, 64, 3),
                      activation = 'relu'))

W0924 19:45:40.869372 4497221056 deprecation_wrapper.py:119] From /Users/zhongyizhang/env/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0924 19:45:40.875721 4497221056 deprecation_wrapper.py:119] From /Users/zhongyizhang/env/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.



In [13]:
from keras.layers.convolutional import MaxPooling2D
classifier.add(MaxPooling2D(pool_size = (2,2)))

W0924 19:45:41.260447 4497221056 deprecation_wrapper.py:119] From /Users/zhongyizhang/env/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:3976: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.



In [14]:
classifier.add(Conv2D(filters = 64,
                      kernel_size = (3,3),
                      activation = 'relu'))

In [15]:
classifier.add(MaxPooling2D(pool_size = (2,2)))

In [16]:
from keras.layers import Flatten
classifier.add(Flatten())

In [17]:
from keras.layers import Dense
classifier.add(Dense(units = 128,
                     activation = 'relu'))

In [18]:
classifier.add(Dense(units = 4,
                     activation = 'softmax'))

In [19]:
classifier.compile(loss = 'categorical_crossentropy', optimizer='adam', 
                   metrics = ['accuracy'])

W0924 19:45:43.344216 4497221056 deprecation_wrapper.py:119] From /Users/zhongyizhang/env/lib/python3.7/site-packages/keras/optimizers.py:790: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

W0924 19:45:43.365349 4497221056 deprecation_wrapper.py:119] From /Users/zhongyizhang/env/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:3295: The name tf.log is deprecated. Please use tf.math.log instead.



In [20]:
classifier.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 62, 62, 32)        896       
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 31, 31, 32)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 29, 29, 64)        18496     
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 14, 14, 64)        0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 12544)             0         
_________________________________________________________________
dense_1 (Dense)              (None, 128)               1605760   
_________________________________________________________________
dense_2 (Dense)              (None, 4)                 516       
Total para

# 3. Model Runs: 
This will be run various times with different numbers of steps_per_epoch and epochs. 

In [21]:
# 3-(a)
import copy
classifier0 = copy.deepcopy(classifier)
classifier0.fit_generator(generator=train_generator, steps_per_epoch=10, 
                          epochs=10)

W0924 19:45:53.922466 4497221056 deprecation_wrapper.py:119] From /Users/zhongyizhang/env/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:174: The name tf.get_default_session is deprecated. Please use tf.compat.v1.get_default_session instead.

W0924 19:45:54.209794 4497221056 deprecation.py:323] From /Users/zhongyizhang/env/lib/python3.7/site-packages/tensorflow/python/ops/math_grad.py:1250: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


Epoch 1/10
10/10 [==============================] - 4s 361ms/step - loss: 0.8945 - acc: 0.6288
Epoch 2/10
10/10 [==============================] - 4s 356ms/step - loss: 0.1925 - acc: 0.9449
Epoch 3/10
10/10 [==============================] - 3s 341ms/step - loss: 0.0661 - acc: 0.9801
Epoch 4/10
10/10 [==============================] - 3s 348ms/step - loss: 0.0412 - acc: 0.9865
Epoch 5/10
10/10 [==============================] - 4s 358ms/step - loss: 0.0260 - acc: 0.9887
Epoch 6/10
10/10 [==============================] - 3s 344ms/step - loss: 0.0136 - acc: 1.0000
Epoch 7/10
10/10 [==============================] - 4s 352ms/step - loss: 0.0054 - acc: 1.0000
Epoch 8/10
10/10 [==============================] - 4s 357ms/step - loss: 0.0064 - acc: 0.9969
Epoch 9/10
10/10 [==============================] - 3s 333ms/step - loss: 0.0031 - acc: 1.0000
Epoch 10/10
10/10 [==============================] - 3s 348ms/step - loss: 0.0037 - acc: 1.0000


In [28]:
# import os, glob
# import numpy as np
# from keras.models import model_from_yaml
# from keras.preprocessing import image

# image_dir = '/Users/zhongyizhang/Desktop/dataset_test/'
# data_path = os.path.join()

In [29]:
# 3-(b)
# write model and model weights to disk
from keras.models import model_from_yaml
model_yaml = classifier0.to_yaml()
with open("model_1.yaml", "w") as yaml_file:
    yaml_file.write(model_yaml)
    classifier0.save_weights("model_1.h5")
    print("Saved model to disk")

Saved model to disk


In [32]:
# 3-(c)
import os, glob
import numpy as np
from keras.models import model_from_yaml
from keras.preprocessing import image

# load model from disk
yaml_file = open('model_1.yaml', 'r')
loaded_model_yaml = yaml_file.read()
yaml_file.close()
model = model_from_yaml(loaded_model_yaml)
# load weights into new model
model.load_weights("model_1.h5")
print("Loaded model from disk")

# test data path
img_dir = "/Users/zhongyizhang/Desktop/UChicago_MSBI/2019Summer/Machine Learning/HWK8/dataset_test/" # Enter Directory of all images

# iterate over each test image
# make a prediction and add to results 
data_path = os.path.join(img_dir, '*g')
files = glob.glob(data_path)
data = []
results = []
for f1 in files:
    img = image.load_img(f1, target_size = (64, 64))
    img = image.img_to_array(img)
    img = np.expand_dims(img, axis = 0)
    data.append(img)
    result = model.predict(img)
    r = np.argmax(result, axis=1)
    results.append(r)

results

/Users/zhongyizhang/env/lib/python3.7/site-packages/keras/engine/saving.py:473: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(yaml_string)


Loaded model from disk


[array([3]),
 array([0]),
 array([3]),
 array([0]),
 array([1]),
 array([2]),
 array([1]),
 array([1])]

In [33]:
train_generator.class_indices

{'category 1': 0, 'category 2': 1, 'category 3': 2, 'category 4': 3}

In [34]:
result_list1 = [str(results[0])[1], str(results[1])[1], str(results[2])[1], 
                str(results[3])[1], str(results[4])[1], str(results[5])[1], 
                str(results[6])[1], str(results[7])[1]]

In [35]:
# 3-(d)
from tabulate import tabulate
print(tabulate([['1022.png', 0, result_list1[0]], 
                ['1053.png', 0, result_list1[1]], 
                ['4011.png', 2, result_list1[2]], 
                ['4053.png', 2, result_list1[3]], 
                ['6023.png', 1, result_list1[4]], 
                ['6051.png', 1, result_list1[5]], 
                ['C014.png', 3, result_list1[6]], 
                ['C033.png', 3, result_list1[7]]],
                headers = ['File Nmae', 'Real Category','Predict Category']))

File Nmae      Real Category    Predict Category
-----------  ---------------  ------------------
1022.png                   0                   3
1053.png                   0                   0
4011.png                   2                   3
4053.png                   2                   0
6023.png                   1                   1
6051.png                   1                   2
C014.png                   3                   1
C033.png                   3                   1


From the dataset_test folder and what I observed, I see:          
file_name   real    pred      
1022.png  -  0   -   3      
1053.png  -  0   -   0      
4011.png  -  2   -   0      
4053.png  -  2   -   0        
6023.png  -  1   -   1     
6051.png  -  1   -   2     
C014.png  -  3   -   1      
C033.png  -  3   -   1          
#### The classifier model I created correctly predicted 1053.png and 6023.png. The accuracy is 2/8 = 1/4 = 0.25 = 25%. The accuracy for "steps_per_epoch = 10 and epochs = 10" is 25%.

In [25]:
# To test (steps_per_epoch: 30, epochs: 30) independently.
import copy
classifier00 = copy.deepcopy(classifier)
classifier00.fit_generator(generator=train_generator, steps_per_epoch=30, 
                           epochs=30)

Epoch 1/30
30/30 [==============================] - 11s 352ms/step - loss: 0.3948 - acc: 0.8628
Epoch 2/30
30/30 [==============================] - 11s 357ms/step - loss: 0.0373 - acc: 0.9885
Epoch 3/30
30/30 [==============================] - 11s 356ms/step - loss: 0.0074 - acc: 1.0000
Epoch 4/30
30/30 [==============================] - 10s 349ms/step - loss: 0.0198 - acc: 0.9951
Epoch 5/30
30/30 [==============================] - 11s 353ms/step - loss: 0.0034 - acc: 1.0000
Epoch 6/30
30/30 [==============================] - 10s 349ms/step - loss: 0.0019 - acc: 1.0000
Epoch 7/30
30/30 [==============================] - 10s 349ms/step - loss: 4.7242e-04 - acc: 1.0000
Epoch 8/30
30/30 [==============================] - 10s 346ms/step - loss: 2.0162e-04 - acc: 1.0000
Epoch 9/30
30/30 [==============================] - 10s 345ms/step - loss: 1.4430e-04 - acc: 1.0000
Epoch 10/30
30/30 [==============================] - 10s 348ms/step - loss: 1.0929e-04 - acc: 1.0000
Epoch 11/30
30/30 [====

In [26]:
img_dir = "/Users/zhongyizhang/Desktop/dataset_test/" # Enter Directory of all images

# iterate over each test image
# make a prediction and add to results 
data_path = os.path.join(img_dir, '*g')
files = glob.glob(data_path)
data = []
results = []
for f1 in files:
    img = image.load_img(f1, target_size = (64, 64))
    img = image.img_to_array(img)
    img = np.expand_dims(img, axis = 0)
    data.append(img)
    result = classifier00.predict(img)
    r = np.argmax(result, axis=1)
    results.append(r)

results

[array([3]),
 array([0]),
 array([0]),
 array([0]),
 array([1]),
 array([2]),
 array([1]),
 array([1])]

In [27]:
# 3-(e) from here
step_list = [10, 10, 30, 30, 30, 50, 50, 50]
epoch_list = [20, 30, 10, 20, 30, 10, 20, 30]
result_list = ['r2', 'r3', 'r4', 'r5', 'r6', 'r7', 'r8', 'r9']

# step_list = [2, 10]
# epoch_list = [10, 2]
# result_list = ['r1', 'r2']
# range_l = [1, 2]

In [28]:
for i, j, k, l in zip(step_list, epoch_list, result_list, list(range(2,10))):
    classifier1 = copy.deepcopy(classifier)
    classifier1.fit_generator(generator=train_generator, steps_per_epoch=i, 
                              epochs=j)
    img_dir = "/Users/zhongyizhang/Desktop/dataset_test/" # Enter Directory of all images

    data_path = os.path.join(img_dir, '*g')
    files = glob.glob(data_path)
    data = []
    k = []
    for f1 in files:
        img = image.load_img(f1, target_size = (64, 64))
        img = image.img_to_array(img)
        img = np.expand_dims(img, axis = 0)
        data.append(img)
        result = classifier1.predict(img)
        r = np.argmax(result, axis=1)
        k.append(r)
    print('result_list',l, '=',k)

Epoch 1/20
10/10 [==============================] - 4s 351ms/step - loss: 0.8812 - acc: 0.6895
Epoch 2/20
10/10 [==============================] - 3s 331ms/step - loss: 0.2196 - acc: 0.9220
Epoch 3/20
10/10 [==============================] - 4s 355ms/step - loss: 0.0990 - acc: 0.9688
Epoch 4/20
10/10 [==============================] - 4s 353ms/step - loss: 0.0281 - acc: 0.9937
Epoch 5/20
10/10 [==============================] - 4s 354ms/step - loss: 0.0301 - acc: 0.9886
Epoch 6/20
10/10 [==============================] - 3s 349ms/step - loss: 0.0214 - acc: 0.9928
Epoch 7/20
10/10 [==============================] - 3s 347ms/step - loss: 0.0185 - acc: 0.9877
Epoch 8/20
10/10 [==============================] - 3s 344ms/step - loss: 0.0057 - acc: 1.0000
Epoch 9/20
10/10 [==============================] - 4s 353ms/step - loss: 0.0028 - acc: 1.0000
Epoch 10/20
10/10 [==============================] - 4s 353ms/step - loss: 0.0086 - acc: 0.9937
Epoch 11/20
10/10 [==============================

Epoch 1/30
30/30 [==============================] - 10s 348ms/step - loss: 0.3172 - acc: 0.8876
Epoch 2/30
30/30 [==============================] - 10s 349ms/step - loss: 0.0405 - acc: 0.9854
Epoch 3/30
30/30 [==============================] - 10s 350ms/step - loss: 0.0098 - acc: 0.9972
Epoch 4/30
30/30 [==============================] - 10s 349ms/step - loss: 0.0015 - acc: 1.0000
Epoch 5/30
30/30 [==============================] - 10s 345ms/step - loss: 0.0011 - acc: 1.0000
Epoch 6/30
30/30 [==============================] - 10s 346ms/step - loss: 5.0808e-04 - acc: 1.0000
Epoch 7/30
30/30 [==============================] - 10s 347ms/step - loss: 8.9472e-04 - acc: 1.0000
Epoch 8/30
30/30 [==============================] - 10s 347ms/step - loss: 3.5568e-04 - acc: 1.0000
Epoch 9/30
30/30 [==============================] - 10s 346ms/step - loss: 2.1264e-04 - acc: 1.0000
Epoch 10/30
30/30 [==============================] - 10s 348ms/step - loss: 1.2981e-04 - acc: 1.0000
Epoch 11/30
30/30 [

Now I have following results except for (steps_per_epoch: 50, epochs: 100, I will run this time-consuming one independently)        
result_list1 = [array([3]), array([0]), array([0]), array([0]), array([1]), array([2]), array([1]), array([1])]       
result_list2 = [array([3]), array([0]), array([0]), array([0]), array([1]), array([2]), array([1]), array([1])]       
result_list3 = [array([3]), array([0]), array([1]), array([0]), array([1]), array([2]), array([1]), array([1])]      
result_list4 = [array([3]), array([0]), array([0]), array([0]), array([1]), array([2]), array([1]), array([1])]       
result_list5 = [array([3]), array([0]), array([0]), array([0]), array([1]), array([2]), array([1]), array([1])]       
result_list6 = [array([3]), array([0]), array([3]), array([0]), array([1]), array([2]), array([1]), array([1])]       
result_list7 = [array([3]), array([0]), array([0]), array([0]), array([1]), array([2]), array([1]), array([1])]        
result_list8 = [array([3]), array([0]), array([2]), array([0]), array([1]), array([2]), array([1]), array([1])]        
result_list9 = [array([3]), array([0]), array([0]), array([0]), array([1]), array([2]), array([1]), array([1])]        

In [29]:
# 3-(a)
classifier2=copy.deepcopy(classifier)
classifier2.fit_generator(generator=train_generator, steps_per_epoch=50, 
                          epochs=100)

Epoch 1/100
50/50 [==============================] - 18s 352ms/step - loss: 0.2435 - acc: 0.9108
Epoch 2/100
50/50 [==============================] - 18s 357ms/step - loss: 0.0079 - acc: 0.9987
Epoch 3/100
50/50 [==============================] - 18s 357ms/step - loss: 0.0030 - acc: 1.0000
Epoch 4/100
50/50 [==============================] - 17s 345ms/step - loss: 3.0245e-04 - acc: 1.0000
Epoch 5/100
50/50 [==============================] - 17s 346ms/step - loss: 1.9619e-04 - acc: 1.0000
Epoch 6/100
50/50 [==============================] - 17s 348ms/step - loss: 1.2140e-04 - acc: 1.0000
Epoch 7/100
50/50 [==============================] - 18s 357ms/step - loss: 6.7478e-05 - acc: 1.0000
Epoch 8/100
50/50 [==============================] - 18s 366ms/step - loss: 4.2527e-05 - acc: 1.0000
Epoch 9/100
50/50 [==============================] - 18s 358ms/step - loss: 3.3960e-05 - acc: 1.0000
Epoch 10/100
50/50 [==============================] - 18s 355ms/step - loss: 9.1267e-05 - acc: 1.0000
E

In [31]:
img_dir = "/Users/zhongyizhang/Desktop/dataset_test/" # Enter Directory of all images

# iterate over each test image
# make a prediction and add to results 
data_path = os.path.join(img_dir, '*g')
files = glob.glob(data_path)
data = []
results = []
for f1 in files:
    img = image.load_img(f1, target_size = (64, 64))
    img = image.img_to_array(img)
    img = np.expand_dims(img, axis = 0)
    data.append(img)
    result = classifier2.predict(img)
    r = np.argmax(result, axis=1)
    results.append(r)

results

[array([3]),
 array([0]),
 array([0]),
 array([0]),
 array([1]),
 array([2]),
 array([1]),
 array([1])]

In conclusion I have foloowing results by running：       
(steps_per_epoch: 10, epochs: 10)      
(steps_per_epoch: 10, epochs: 20)      
(steps_per_epoch: 10, epochs: 30)      
(steps_per_epoch: 30, epochs: 10)        
(steps_per_epoch: 30, epochs: 20)      
(steps_per_epoch: 30, epochs: 30)         
(steps_per_epoch: 50, epochs: 10)      
(steps_per_epoch: 50, epochs: 20)      
(steps_per_epoch: 50, epochs: 30)       
(steps_per_epoch: 50, epochs: 100)        

result_list1 = [array([3]), array([0]), array([0]), array([0]), array([1]), array([2]), array([1]), array([1])]          
result_list2 = [array([3]), array([0]), array([0]), array([0]), array([1]), array([2]), array([1]), array([1])]        
result_list3 = [array([3]), array([0]), array([1]), array([0]), array([1]), array([2]), array([1]), array([1])]       
result_list4 = [array([3]), array([0]), array([0]), array([0]), array([1]), array([2]), array([1]), array([1])]          
result_list5 = [array([3]), array([0]), array([0]), array([0]), array([1]), array([2]), array([1]), array([1])]            
result_list6 = [array([3]), array([0]), array([3]), array([0]), array([1]), array([2]), array([1]), array([1])]           
result_list7 = [array([3]), array([0]), array([0]), array([0]), array([1]), array([2]), array([1]), array([1])]            
result_list8 = [array([3]), array([0]), array([2]), array([0]), array([1]), array([2]), array([1]), array([1])]          
result_list9 = [array([3]), array([0]), array([0]), array([0]), array([1]), array([2]), array([1]), array([1])]          
result_list10 = [array([3]), array([0]), array([0]), array([0]), array([1]), array([2]), array([1]), array([1])]

In [43]:
# result_list1 = [array([3]), array([0]), array([0]), array([0]), array([1]), array([2]), array([1]), array([1])]
# result_list2 = [array([3]), array([0]), array([0]), array([0]), array([1]), array([2]), array([1]), array([1])]
# result_list3 = [array([3]), array([0]), array([1]), array([0]), array([1]), array([2]), array([1]), array([1])]
# result_list4 = [array([3]), array([0]), array([0]), array([0]), array([1]), array([2]), array([1]), array([1])]
# result_list5 = [array([3]), array([0]), array([0]), array([0]), array([1]), array([2]), array([1]), array([1])]
# result_list6 = [array([3]), array([0]), array([3]), array([0]), array([1]), array([2]), array([1]), array([1])]
# result_list7 = [array([3]), array([0]), array([0]), array([0]), array([1]), array([2]), array([1]), array([1])]
# result_list8 = [array([3]), array([0]), array([2]), array([0]), array([1]), array([2]), array([1]), array([1])]
# result_list9 = [array([3]), array([0]), array([0]), array([0]), array([1]), array([2]), array([1]), array([1])]
# result_list10 = [array([3]), array([0]), array([0]), array([0]), array([1]), array([2]), array([1]), array([1])]

r1 = [3, 0, 0, 0, 1, 2, 1, 1]
r2 = [3, 0, 0, 0, 1, 2, 1, 1]
r3 = [3, 0, 1, 0, 1, 2, 1, 1]
r4 = [3, 0, 0, 0, 1, 2, 1, 1]
r5 = [3, 0, 0, 0, 1, 2, 1, 1]
r6 = [3, 0, 3, 0, 1, 2, 1, 1]
r7 = [3, 0, 0, 0, 1, 2, 1, 1]
r8 = [3, 0, 2, 0, 1, 2, 1, 1]
r9 = [3, 0, 0, 0, 1, 2, 1, 1]
r10 = [3, 0, 0, 0, 1, 2, 1, 1]
print(' r1:', r1,'\n','r2:', r2,'\n','r3:', r3,'\n','r4:', r4,'\n','r5:', r5,'\n',
     'r6:', r6,'\n', 'r7:', r7,'\n','r8:', r8,'\n','r9:', r9,'\n','r10:', r10)


 r1: [3, 0, 0, 0, 1, 2, 1, 1] 
 r2: [3, 0, 0, 0, 1, 2, 1, 1] 
 r3: [3, 0, 1, 0, 1, 2, 1, 1] 
 r4: [3, 0, 0, 0, 1, 2, 1, 1] 
 r5: [3, 0, 0, 0, 1, 2, 1, 1] 
 r6: [3, 0, 3, 0, 1, 2, 1, 1] 
 r7: [3, 0, 0, 0, 1, 2, 1, 1] 
 r8: [3, 0, 2, 0, 1, 2, 1, 1] 
 r9: [3, 0, 0, 0, 1, 2, 1, 1] 
 r10: [3, 0, 0, 0, 1, 2, 1, 1]


Prediction results:           
r1: [3, 0, 0, 0, 1, 2, 1, 1]        
r2: [3, 0, 0, 0, 1, 2, 1, 1]        
r3: [3, 0, 1, 0, 1, 2, 1, 1]       
r4: [3, 0, 0, 0, 1, 2, 1, 1]        
r5: [3, 0, 0, 0, 1, 2, 1, 1]      
r6: [3, 0, 3, 0, 1, 2, 1, 1]       
r7: [3, 0, 0, 0, 1, 2, 1, 1]       
r8: [3, 0, 2, 0, 1, 2, 1, 1]      
r9: [3, 0, 0, 0, 1, 2, 1, 1]      
r10: [3, 0, 0, 0, 1, 2, 1, 1]       
Correct: [0, 0, 2, 2, 1, 1, 3, 3]       

In [47]:
import pandas as pd
data = [[10, 10, 0.25], [10, 20, 0.25], [10, 30, 0.25], [30, 10, 0.25], 
        [30, 20, 0.25], [30, 30, 0.25], [50, 10, 0.25], [50, 20, 0.375],
        [50, 30, 0.25], [50, 100, 0.25]] 
  

df0 = pd.DataFrame(data, columns = ['Steps per Epoch', 'Epochs', 'Accuracy'])


In [48]:
df0

Steps per Epoch  Epochs  Accuracy
0               10      10     0.250
1               10      20     0.250
2               10      30     0.250
3               30      10     0.250
4               30      20     0.250
5               30      30     0.250
6               50      10     0.250
7               50      20     0.375
8               50      30     0.250
9               50     100     0.250

# Conceptual Questions: 

4. Discuss the effect of the following on accuracy and loss (train & test): 

Increasing the steps_per_epoch
Increasing the number of epochs
5. Name two uses of zero padding in CNN.

6. What is the use of a 1 x 1 kernel in CNN? 

7. What are the advantages of a CNN over a fully connected DNN for this image classification problem?

---------------------

### Answers:

4. Higher number of epoch could cause over-fitting. For Steps per epoch, if this parameter is too high, it could also cause over-fitting, although this doesn't clearly show on my running results. As the number of epoch going higher, the accuracy may potentially go even lower. This works the same as the Steps per epoch. 

In conclusion, the accuracy could go higher when the "Steps per Epoch" parameter goes up and the "Epoches" parameter goes up. However, these two parameters go up also causes the over-fitting. Moreover, the accuracy could decrease again if the "Steps per Epoch" parameter and the "Epoches" parameter goes up too high. There are optimal values for these two paramters.

5. Zero-padding refers to the process of symmetrically adding zeroes to the input matrix. It's a commonly used modification that allows the size of the input to be adjusted to our requirement. It is mostly used in designing the CNN layers when the dimensions of the input volume need to be preserved in the output volume.

For two uses:
Zero-padding is a generic way to:         
(1) control the shrinkage of dimension after applying filters larger than 1x1          
(2) avoid loosing information at the boundaries, e.g. when weights in a filter drop rapidly away from its center.

For a specific input, activation function, or loss function, a variant might perform better, i.e. utilizing domain knowledge. However, the key for zero-padding is "being generic". For example, a completely different padding would be "reflection padding" that, instead of a specific value, puts a mirror of input outside the boundaries. We could try reflection padding and if it gives better results, then we might look for a justification based on the task, activation function, etc.

6. 1 x 1 conv filters can be used to change the dimensionality in the filter space. If 𝐹1>𝐹 then we are increasing dimensionality, if 𝐹1<𝐹 we are decreasing dimensionality, in the filter dimension. 1 x 1 convolutions are used to compute reductions before the expensive 3x3 and 5x5 convolutions. 

In the Inception architecture, I can use the 1 x 1 convolutional filters to reduce dimensionality in the filter dimension. These 1 x 1 conv layers can be used in general to change the filter space dimensionality (either increase or decrease) and in the Inception architecture, I can see how effective these 1 x 1 filters can be for dimensionality reduction, explicitly in the filter dimension space, not the spatial dimension space.

7. Fully connected neural networks are good enough classifiers. However, they aren't good for feature extraction. Before the emergence on CNNs, the state-of-the-art was to extract explicit features from images and then classify these features.

CNNs are trained to identify and extract the best features from the images for the problem at hand. That is their main strength. The latter layers of a CNN are fully connected because of their strength as a classifier. So these two architectures aren't competing though as you may think as CNNs incorporate Fully-connected layers.

---------------------------